name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.ouxiang.me", custom_domain = true },
  { pattern = "quay.ouxiang.me", custom_domain = true },
  { pattern = "gcr.ouxiang.me", custom_domain = true },
  { pattern = "k8s-gcr.ouxiang.me", custom_domain = true },
  { pattern = "k8s.ouxiang.me", custom_domain = true },
  { pattern = "ghcr.ouxiang.me", custom_domain = true },
  { pattern = "cloudsmith.ouxiang.me", custom_domain = true },
  { pattern = "dockerhub.ouxiang.me", custom_domain = true },
  { pattern = "docker-ce.ouxiang.me", custom_domain = true },
  { pattern = "github.ouxiang.me", custom_domain = true },
  { pattern = "huggingface.ouxiang.me", custom_domain = true},
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""
